# Generated by Django 4.0.3 on 2022-04-09 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_logintable_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='phoneno',
            field=models.BigIntegerField(help_text='format:xxxxxxxxxx,required,unique', validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d$')], verbose_name='Contact No'),
        ),
    ]
